anguage: python
python:
  - "3.8-dev"
install:
  - cp contrib/env-sample .env
  - pip install -r requirements-dev.txt codecov
# command to run tests
script:
  - flake8 .
  - pycodestyle .
  - coverage run -m pytest -v --doctest-glob='*.md'
after_success:
  - codecov