language: python
python:
  - "3.8-dev"
services:
  postgresql
addons:
  postgresql: '9.5'
install:
  - cp contrib/env-sample .env
  - pip install -r requirements-dev.txt codecov
before_script:
  - psql -c "CREATE DATABASE lme;" -U postgres
  - python -c 'from lme.db import create;create()'
# command to run tests
script:
  - flake8 .
  - pycodestyle .
  - coverage run -m pytest -v --doctest-glob='*.md'
after_success:
  - codecov